# Generated by Django 5.1.5 on 2025-02-09 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0003_studentdiscussion_discussionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'National ID Card'), ('MATRIC', 'Matric/O-Level Certificate'), ('FSC', 'FSC/A-Level Certificate'), ('DAE', 'DAE Certificate'), ('BACH_DEGREE', "Bachelor's Degree"), ('BACH_TRANSCRIPT', "Bachelor's Transcript"), ('MASTER_DEGREE', "Master's/MPhil Degree"), ('MASTER_TRANSCRIPT', "Master's/MPhil Transcript"), ('LOR', 'Letter of Recommendation'), ('SOP', 'Statement of Purpose'), ('EXP_CERT', 'Experience Certificate'), ('MEDICAL', 'Medical Certificate'), ('CV', 'CV/Resume'), ('PROJECTS', 'Soft Copies of Projects'), ('PUBLICATIONS', 'International Publications')], max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.student')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='document_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='consultancy.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
