# Generated by Django 5.1.5 on 2025-02-15 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0004_documentrequest_documentversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('processing_edit_student', 'Can edit student details as processing team')]},
        ),
        migrations.CreateModel(
            name='StudentUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.student')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
