# Generated by Django 5.1.5 on 2025-02-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy', '0005_alter_student_options_studentupdatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'National ID Card'), ('MATRIC', 'Matric/O-Level Certificate'), ('FSC', 'FSC/A-Level Certificate'), ('DAE', 'DAE Certificate'), ('BACH_DEGREE', "Bachelor's Degree"), ('BACH_TRANSCRIPT', "Bachelor's Transcript"), ('MASTER_DEGREE', "Master's/MPhil Degree"), ('MASTER_TRANSCRIPT', "Master's/MPhil Transcript"), ('LOR', 'Letter of Recommendation'), ('SOP', 'Statement of Purpose'), ('EXP_CERT', 'Experience Certificate'), ('MEDICAL', 'Medical Certificate'), ('CV', 'CV/Resume'), ('PROJECTS', 'Soft Copies of Projects'), ('PUBLICATIONS', 'International Publications'), ('CUSTOM', 'Custom Document')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultancy.student'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'National ID Card'), ('MATRIC', 'Matric/O-Level Certificate'), ('FSC', 'FSC/A-Level Certificate'), ('DAE', 'DAE Certificate'), ('BACH_DEGREE', "Bachelor's Degree"), ('BACH_TRANSCRIPT', "Bachelor's Transcript"), ('MASTER_DEGREE', "Master's/MPhil Degree"), ('MASTER_TRANSCRIPT', "Master's/MPhil Transcript"), ('LOR', 'Letter of Recommendation'), ('SOP', 'Statement of Purpose'), ('EXP_CERT', 'Experience Certificate'), ('MEDICAL', 'Medical Certificate'), ('CV', 'CV/Resume'), ('PROJECTS', 'Soft Copies of Projects'), ('PUBLICATIONS', 'International Publications'), ('CUSTOM', 'Custom Document')], max_length=50),
        ),
    ]
