version: '3.7'

services:
  django_gunicorn:
    image: deveaselabs/django-gunicorn:latest
    volumes:
      - static:/static
      - media:/media
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: deveaselabs/nginx:latest
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports: 
      - "4000:80"
    depends_on:
      - django_gunicorn

  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  static:
  media:
  postgres_data: