name: Edenz Portal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker Images
        run: docker-compose -f docker-compose.yml build

      - name: Push Docker Images
        run: docker-compose -f docker-compose.yml push
      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Images
        run: echo "${{ secrets.USER_PASSWORD }}" | sudo -S docker-compose -f ./docker-compose.yml pull

      - name: Stop Previous Compose
        run: echo "${{ secrets.USER_PASSWORD }}" | sudo -S docker-compose down || true

      - name: Run Images
        run: echo "${{ secrets.USER_PASSWORD }}" | sudo -S docker-compose up -d